spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/wot
    username: sa
    password:
    driverClassName: org.h2.Driver
    initialization-mode: always

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
