insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
values ('AMX 12t', '1', '0', '1', 'FRENCH', '1', '1', '100', 'LIGHT', '0', '0', '0');
insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
values ('AMX 40', '0', '0', '1', 'FRENCH', '1', '1', '100', 'LIGHT', 'RESEARCH', '2', '0', '0');
insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
values ('D1', '0', '0', '1', 'FRENCH', '1', '1', '100', 'LIGHT', '0', '0', '0');
insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
values ('Hotchkiss H38', '0', '0', '1', 'FRENCH', '1', '1', '100', 'LIGHT', 'REINFORCEMENTS', '1', '0', '0');
insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
values ('AMX 13-90', '1', '0', '1', 'FRENCH', '1', '1', '100', 'LIGHT', 'RECRUITMENT', '0', '0', '0');
insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
values ('AMX 13-75', '1', '0', '1', 'FRENCH', '1', '1', '100', 'LIGHT', 'REINFORCEMENTS', '1', '0', '0');
insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
values ('Hotchkiss H39', '0', '0', '1', 'FRENCH', '1', '1', '100', 'LIGHT', 'DISASSEMBLY', '0', '0', '0');
insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
values ('AMX 38', '0', '0', '1', 'FRENCH', '1', '1', '100', 'LIGHT', 'SCOUT', '0', '0', '0');
insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
values ('Hotchkiss H35', '0', '0', '1', 'FRENCH', '1', '1', '100', 'LIGHT', 'RECRUITMENT', '0', '0', '0');
insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
values ('Bat Chatillon 25t', '2', '0', '3', 'FRENCH', '1', '2', '100', 'MEDIUM', 'DISASSEMBLY', '0', '0', '0');
insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
values ('Renault G1R', '2', '0', '3', 'FRENCH', '1', '2', '100', 'MEDIUM', 'REINFORCEMENTS', '3', '0', '0');
insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
values ('Lorraine 40t', '2', '0', '3', 'FRENCH', '1', '2', '100', 'MEDIUM', 'SIEGE', '0', '0', '0');
insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
values ('D2', '2', '0', '3', 'FRENCH', '1', '2', '100', 'MEDIUM', '0','0', '0');
insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
values ('AMX M4', '5', '0', '6', 'FRENCH', '2', '2', '100', 'HEAVY', 'INDESTRUCTIBILITY', '0', '0', '0');
insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
values ('B1', '3', '0', '4', 'FRENCH', '2', '2', '100', 'HEAVY', '0', '0', '0');
insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
values ('ARL 44', '4', '0', '5', 'FRENCH', '2', '2', '100', 'HEAVY', 'REINFORCEMENTS', '3', '0', '0');
insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
values ('Panzejäger 35R', '1', '0', '2', 'FRENCH', '2', '1', '100', 'TANK_DESTROYER', 'REINFORCEMENTS', '2', '0', '0');
insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
values ('AMX 13 FL 11', '1', '0', '2', 'FRENCH', '2', '1', '100', 'TANK_DESTROYER', 'RESEARCH', '3', '0', '0');
insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
values ('Lorraine 37 LAC', '1', '0', '2', 'FRENCH', '2', '1', '100', 'TANK_DESTROYER', 'SABOTAGE', '0', '0', '0');
insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
values ('Lorraine 39 LAM', '1', '0', '2', 'FRENCH', '2', '1', '100', 'ARTILLERY', 'DISASSEMBLY', '0', '0', '0');
insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
values ('Renault BS', '1', '0', '2', 'FRENCH', '2', '1', '100', 'ARTILLERY', '0', '0', '0');
insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
values ('Lorraine 155', '2', '0', '3', 'FRENCH', '2', '1', '100', 'ARTILLERY', 'DISASSEMBLY', '0', '0', '0');
insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
values ('AMX 105', '2', '0', '3', 'FRENCH', '2', '1', '100', 'ARTILLERY', '0', '0', '0');
insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
values ('Canon de 155 mm', '0', '0', '0', 'FRENCH', '1', '0', '100', 'SPECIAL', 'RECRUITMENT', '0', '0', '0');
insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
values ('CT Classe Jaguar', '5', '1', '1', 'FRENCH', '1', '0', '100', 'SPECIAL', '0', '0', '0');
insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, SKILL2, SKILL2_VALUE, DEFENDING_CARD_ID)
values ('Troupes de marine', '1', '0', '0', 'FRENCH', '0', '0', '100', 'SPECIAL', 'SCOUT', '0', 'RECRUITMENT', '0', '0');

-- -- Russian
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, DEFENDING_CARD_ID)
-- values ('T-46', '0', '0', '1', 'RUSSIA', '1', '1', '100', 'LIGHT', 'REINFORCEMENTS', '1', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, DEFENDING_CARD_ID)
-- values ('T-127', '0', '0', '1', 'RUSSIA', '1', '1', '100', 'LIGHT', 'RESEARCH', '2', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, DEFENDING_CARD_ID)
-- values ('BT-2', '0', '0', '1', 'RUSSIA', '1', '1', '100', 'LIGHT', 'SCOUT', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, DEFENDING_CARD_ID)
-- values ('T-26', '0', '0', '1', 'RUSSIA', '1', '1', '100', 'LIGHT', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, DEFENDING_CARD_ID)
-- values ('T-44', '2', '0', '3', 'RUSSIA', '1', '2', '100', 'MEDIUM', 'DISASSEMBLY', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, DEFENDING_CARD_ID)
-- values ('T-28', '2', '0', '3', 'RUSSIA', '1', '2', '100', 'MEDIUM', 'SIEGE', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, DEFENDING_CARD_ID)
-- values ('T-34', '2', '0', '3', 'RUSSIA', '1', '2', '100', 'MEDIUM', 'RESEARCH', '4', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, DEFENDING_CARD_ID)
-- values ('T-44-85', '2', '0', '3', 'RUSSIA', '1', '2', '100', 'REINFORCEMENTS', '2', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, DEFENDING_CARD_ID)
-- values ('KV-2', '4', '0', '5', 'RUSSIA', '2', '2', '100', 'HEAVY', 'REINFORCEMENTS', '3', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, DEFENDING_CARD_ID)
-- values ('KV-1S', '3', '0', '4', 'RUSSIA', '2', '2', '100', 'HEAVY', 'DISASSEMBLY', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, DEFENDING_CARD_ID)
-- values ('KV-220', '5', '0', '6', 'RUSSIA', '2', '2', '100', 'HEAVY', 'INDESTRUCTIBILITY', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, DEFENDING_CARD_ID)
-- values ('SU-76', '1', '0', '2', 'RUSSIA', '2', '1', '100', 'TANK_DESTROYER', 'RESEARCH', '3', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, DEFENDING_CARD_ID)
-- values ('SU-85', '2', '0', '3', 'RUSSIA', '2', '1', '100', 'TANK_DESTROYER', 'RECRUITMENT', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, DEFENDING_CARD_ID)
-- values ('SU-100', '3', '0', '4', 'RUSSIA', '2', '1', '100', 'TANK_DESTROYER', 'REINFORCEMENTS', '3', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, DEFENDING_CARD_ID)
-- values ('SU-8', '1', '0', '2', 'RUSSIA', '2', '1', '100', 'ARTILLERY', 'DISASSEMBLY', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, DEFENDING_CARD_ID)
-- values ('S-51', '3', '0', '4', 'RUSSIA', '2', '1', '100', 'ARTILLERY', 'SABOTAGE', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, DEFENDING_CARD_ID)
-- values ('SU-5', '1', '0', '2', 'RUSSIA', '2', '1', '100', 'ARTILLERY', 'SCOUT', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, DEFENDING_CARD_ID)
-- values ('SU-18', '1', '0', '2', 'RUSSIA', '2', '1', '100', 'ARTILLERY', 'REINFORCEMENTS', '1', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, DEFENDING_CARD_ID)
-- values ('SU-14', '3', '0', '4', 'RUSSIA', '2', '1', '100', 'ARTILLERY', 'DISASSEMBLY', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, DEFENDING_CARD_ID)
-- values ('SU-26', '1', '0', '2', 'RUSSIA', '2', '1', '100', 'ARTILLERY', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, DEFENDING_CARD_ID)
-- values ('ZiS-5', '4', '1', '0', 'RUSSIA', '0', '1', '100', 'SPECIAL', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL2, DEFENDING_CARD_ID)
-- values ('SMERSH', '1', '0', '0', 'RUSSIA', '0', '0', '100', 'SPECIAL', 'SCOUT', 'SABOTAGE', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, DEFENDING_CARD_ID)
-- values ('19-K 45 mm', '0', '0', '0', 'RUSSIA', '1', '0', '100', 'SPECIAL', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, DEFENDING_CARD_ID)
-- values ('U-2', '6', '1', '1', 'RUSSIA', '0', '0', '100', 'SPECIAL', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, DEFENDING_CARD_ID)
-- values ('TM-57', '1', '0', '0', 'RUSSIA', '2', '0', '100', 'SPECIAL', 'VEHICLE_ATTACK', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, DEFENDING_CARD_ID)
-- values ('53-K 45 mm', '0', '0', '0', 'RUSSIA', '1', '0', '100', 'SPECIAL', 'RECRUITMENT', '0');
--
-- -- German
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, DEFENDING_CARD_ID)
-- values ('PzKpfw II C', '0', '0', '1', 'GERMAN', '1', '1', '100', 'LIGHT', 'REINFORCEMENTS', '1', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, DEFENDING_CARD_ID)
-- values ('PzKpfw II Luchs', '0', '0', '1', 'GERMAN', '1', '1', '100', 'LIGHT', 'SCOUT', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, DEFENDING_CARD_ID)
-- values ('PzKpfw I', '0', '0', '1', 'GERMAN', '1', '1', '100', 'LIGHT', 'RECRUITMENT', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, DEFENDING_CARD_ID)
-- values ('PzKpfw 38(t)', '0', '0', '1', 'GERMAN', '1', '1', '100', 'LIGHT', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, DEFENDING_CARD_ID)
-- values ('PzKpfw II F', '0', '0', '1', 'GERMAN', '1', '1', '100', 'LIGHT', 'DISASSEMBLY', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, DEFENDING_CARD_ID)
-- values ('PzKpfw II J', '0', '0', '1', 'GERMAN', '1', '1', '100', 'LIGHT', 'RESEARCH', '2', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, DEFENDING_CARD_ID)
-- values ('PzKpfw III/IV', '1', '0', '2', 'GERMAN', '1', '2', '100', 'MEDIUM', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, DEFENDING_CARD_ID)
-- values ('PzKpfw V Panther', '2', '0', '3', 'GERMAN', '1', '2', '100', 'MEDIUM', 'REINFORCEMENTS', '2', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, DEFENDING_CARD_ID)
-- values ('PzKpfw IV', '2', '0', '3', 'GERMAN', '1', '2', '100', 'MEDIUM', 'RESEARCH', '4', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, DEFENDING_CARD_ID)
-- values ('VK3002 (DB)', '3', '0', '4', 'GERMAN', '1', '2', '100', 'MEDIUM', 'SIEGE', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, DEFENDING_CARD_ID)
-- values ('VK3001 (P)', '3', '0', '4', 'GERMAN', '1', '2', '100', 'MEDIUM', 'DISASSEMBLY', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, DEFENDING_CARD_ID)
-- values ('PzKpfw VII Löwe', '4', '0', '5', 'GERMAN', '2', '2', '100', 'HEAVY', 'DISASSEMBLY', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, DEFENDING_CARD_ID)
-- values ('PzKpfw VI Tiger', '3', '0', '4', 'GERMAN', '2', '2', '100', 'HEAVY', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, DEFENDING_CARD_ID)
-- values ('PzKpfw VI-B Tiger II', '4', '0', '5', 'GERMAN', '2', '2', '100', 'HEAVY', 'REINFORCEMENTS', '3', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, DEFENDING_CARD_ID)
-- values ('PzKpfw VIII Maus', '5', '0', '6', 'GERMAN', '2', '2', '100', 'HEAVY', 'INDESTRUCTIBILITY', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, DEFENDING_CARD_ID)
-- values ('Marder II', '1', '0', '2', 'GERMAN', '2', '1', '100', 'TANK_DESTROYER', 'SABOTAGE', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, DEFENDING_CARD_ID)
-- values ('Jagdpanzer IV', '3', '0', '4', 'GERMAN', '2', '1', '100', 'TANK_DESTROYER', 'RESEARCH', '5', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, DEFENDING_CARD_ID)
-- values ('Jagdpanther', '3', '0', '4', 'GERMAN', '2', '1', '100', 'TANK_DESTROYER', 'RECRUITMENT', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, DEFENDING_CARD_ID)
-- values ('Ferdinand', '4', '0', '5', 'GERMAN', '2', '1', '100', 'TANK_DESTROYER', 'REINFORCEMENTS', '3', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, DEFENDING_CARD_ID)
-- values ('StuG III', '2', '0', '3', 'GERMAN', '2', '1', '100', 'TANK_DESTROYER', 'RECRUITMENT', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, DEFENDING_CARD_ID)
-- values ('Sturmpanzer II', '1', '0', '2', 'GERMAN', '2', '1', '100', 'ARTILLERY', 'DISASSEMBLY', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, DEFENDING_CARD_ID)
-- values ('Hummel', '2', '0', '3', 'GERMAN', '2', '1', '100', 'ARTILLERY', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, DEFENDING_CARD_ID)
-- values ('Sturmpanzer I', '1', '0', '2', 'GERMAN', '2', '1', '100', 'ARTILLERY', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, DEFENDING_CARD_ID)
-- values ('Sturmpanzer 38(t) Grille', '1', '0', '2', 'GERMAN', '2', '1', '100', 'ARTILLERY', 'REINFORCEMENTS', '1', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, DEFENDING_CARD_ID)
-- values ('Opel Blitz', '4', '1', '0', 'GERMAN', '0', '1', '100', 'SPECIAL', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL2, DEFENDING_CARD_ID)
-- values ('Nachrichtenbrigade', '1', '0', '0', 'GERMAN', '0', '0', '100', 'SPECIAL', 'SCOUT', 'SIEGE', '0');
--
-- -- USA
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, DEFENDING_CARD_ID)
-- values ('M2 Light Tank', '0', '0', '1', 'USA', '1', '1', '100', 'LIGHT', 'SABOTAGE', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, DEFENDING_CARD_ID)
-- values ('M3 Stuart', '0', '0', '1', 'USA', '1', '1', '100', 'LIGHT', 'RESEARCH', '2', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, DEFENDING_CARD_ID)
-- values ('T1 Cunningham', '0', '0', '1', 'USA', '1', '1', '100', 'LIGHT', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, DEFENDING_CARD_ID)
-- values ('M5 Stuart', '0', '0', '1', 'USA', '1', '1', '100', 'LIGHT', 'DISASSEMBLY', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, DEFENDING_CARD_ID)
-- values ('M7', '2', '0', '3', 'USA', '1', '2', '100', 'MEDIUM', 'RESEARCH', '4', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, DEFENDING_CARD_ID)
-- values ('M26 Pershing', '2', '0', '3', 'USA', '1', '2', '100', 'MEDIUM', 'SIEGE', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, DEFENDING_CARD_ID)
-- values ('T20', '2', '0', '3', 'USA', '1', '2', '100', 'MEDIUM', 'SABOTAGE', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, DEFENDING_CARD_ID)
-- values ('M4 Sherman', '2', '0', '3', 'USA', '1', '2', '100', 'MEDIUM', 'DISASSEMBLY', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, DEFENDING_CARD_ID)
-- values ('M2 Medium Tank', '1', '0', '2', 'USA', '1', '2', '100', 'MEDIUM', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, DEFENDING_CARD_ID)
-- values ('M3 Lee', '2', '0', '3', 'USA', '1', '2', '100', 'MEDIUM', 'REINFORCEMENTS', '1', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, DEFENDING_CARD_ID)
-- values ('T29', '3', '0', '4', 'USA', '2', '2', '100', 'HEAVY', 'REINFORCEMENTS', '2', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, DEFENDING_CARD_ID)
-- values ('T32', '4', '0', '5', 'USA', '2', '2', '100', 'HEAVY', 'REINFORCEMENTS', '3', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, DEFENDING_CARD_ID)
-- values ('T30', '5', '0', '6', 'USA', '2', '2', '100', 'HEAVY', 'INDESTRUCTIBILITY', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, DEFENDING_CARD_ID)
-- values ('M6', '3', '0', '4', 'USA', '2', '2', '100', 'HEAVY', 'DISASSEMBLY', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, DEFENDING_CARD_ID)
-- values ('T29 E3', '3', '0', '4', 'USA', '2', '2', '100', 'HEAVY', 'RECRUITMENT', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, DEFENDING_CARD_ID)
-- values ('T1 Heavy Tank', '3', '0', '4', 'USA', '2', '2', '100', 'HEAVY', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, DEFENDING_CARD_ID)
-- values ('M36 Slugger', '2', '0', '3', 'USA', '2', '1', '100', 'TANK_DESTROYER', 'SCOUT', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, DEFENDING_CARD_ID)
-- values ('M10 Wolverine', '2', '0', '3', 'USA', '2', '1', '100', 'TANK_DESTROYER', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, DEFENDING_CARD_ID)
-- values ('M41', '1', '0', '2', 'USA', '2', '1', '100', 'ARTILLERY', 'REINFORCEMENTS', '1', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, DEFENDING_CARD_ID)
-- values ('M7 Priest', '2', '0', '3', 'USA', '2', '1', '100', 'ARTILLERY', 'DISASSEMBLY', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, DEFENDING_CARD_ID)
-- values ('M12', '2', '0', '3', 'USA', '2', '1', '100', 'ARTILLERY', 'REINFORCEMENTS', '2', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, DEFENDING_CARD_ID)
-- values ('M37', '1', '0', '2', 'USA', '2', '1', '100', 'ARTILLERY', 'REINFORCEMENTS', '3', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL2, SKILL2_VALUE, DEFENDING_CARD_ID)
-- values ('Airborne', '1', '0', '0', 'USA', '0', '0', '100', 'SPECIAL', 'SCOUT','REINFORCEMENTS', '1', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, DEFENDING_CARD_ID)
-- values ('Bofors 40 mm', '0', '0', '0', 'USA', '1', '0', '100', 'SPECIAL', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, DEFENDING_CARD_ID)
-- values ('M2 Mortar', '1', '0', '0', 'USA', '1', '0', '100', 'SPECIAL', 'BASE_ATTACK', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, DEFENDING_CARD_ID)
-- values ('LongTom 155 mm', '0', '0', '0', 'USA', '1', '0', '100', 'SPECIAL', 'RECRUITMENT', '0');


-- Medals
-- French
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('French Medal', '1', '1', 'FRENCH');
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('French Medal', '1', '1', 'FRENCH');
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('French Medal', '1', '1', 'FRENCH');
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('French Medal', '1', '1', 'FRENCH');
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('French Medal', '1', '1', 'FRENCH');
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('French Medal', '1', '1', 'FRENCH');
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('French Medal', '1', '1', 'FRENCH');
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('French Medal', '1', '1', 'FRENCH');
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('French Medal', '1', '1', 'FRENCH');
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('French Medal', '1', '2', 'FRENCH');
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('French Medal', '1', '2', 'FRENCH');
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('French Medal', '1', '2', 'FRENCH');

-- Russian
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('Russian Medal', '1', '1', 'RUSSIAN');
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('Russian Medal', '1', '1', 'RUSSIAN');
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('Russian Medal', '1', '1', 'RUSSIAN');
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('Russian Medal', '1', '1', 'RUSSIAN');
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('Russian Medal', '1', '1', 'RUSSIAN');
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('Russian Medal', '1', '1', 'RUSSIAN');
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('Russian Medal', '1', '1', 'RUSSIAN');
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('Russian Medal', '1', '1', 'RUSSIAN');
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('Russian Medal', '1', '1', 'RUSSIAN');
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('Russian Medal', '1', '2', 'RUSSIAN');
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('Russian Medal', '1', '2', 'RUSSIAN');
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('Russian Medal', '1', '2', 'RUSSIAN');

-- German
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('German Medal', '1', '1', 'GERMAN');
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('German Medal', '1', '1', 'GERMAN');
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('German Medal', '1', '1', 'GERMAN');
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('German Medal', '1', '1', 'GERMAN');
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('German Medal', '1', '1', 'GERMAN');
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('German Medal', '1', '1', 'GERMAN');
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('German Medal', '1', '1', 'GERMAN');
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('German Medal', '1', '1', 'GERMAN');
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('German Medal', '1', '1', 'GERMAN');
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('German Medal', '1', '2', 'GERMAN');
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('German Medal', '1', '2', 'GERMAN');
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('German Medal', '1', '2', 'GERMAN');

-- USA
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('USA Medal', '1', '1', 'USA');
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('USA Medal', '1', '1', 'USA');
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('USA Medal', '1', '1', 'USA');
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('USA Medal', '1', '1', 'USA');
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('USA Medal', '1', '1', 'USA');
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('USA Medal', '1', '1', 'USA');
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('USA Medal', '1', '1', 'USA');
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('USA Medal', '1', '1', 'USA');
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('USA Medal', '1', '1', 'USA');
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('USA Medal', '1', '2', 'USA');
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('USA Medal', '1', '2', 'USA');
insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
values ('USA Medal', '1', '2', 'USA');


-- Bases
insert into BASE_CARDS (CARD_NAME, MEDAL_VALUE)
values ('Base', '3');
insert into BASE_CARDS (CARD_NAME, MEDAL_VALUE)
values ('Base', '3');
insert into BASE_CARDS (CARD_NAME, MEDAL_VALUE)
values ('Base', '3');
insert into BASE_CARDS (CARD_NAME, MEDAL_VALUE)
values ('Base', '3');
insert into BASE_CARDS (CARD_NAME, MEDAL_VALUE)
values ('Base', '3');
insert into BASE_CARDS (CARD_NAME, MEDAL_VALUE)
values ('Base', '3');
insert into BASE_CARDS (CARD_NAME, MEDAL_VALUE)
values ('Base', '3');
insert into BASE_CARDS (CARD_NAME, MEDAL_VALUE)
values ('Base', '3');
insert into BASE_CARDS (CARD_NAME, MEDAL_VALUE)
values ('Base', '3');
insert into BASE_CARDS (CARD_NAME, MEDAL_VALUE)
values ('Base', '3');
insert into BASE_CARDS (CARD_NAME, MEDAL_VALUE)
values ('Base', '3');
insert into BASE_CARDS (CARD_NAME, MEDAL_VALUE)
values ('Base', '3');
insert into BASE_CARDS (CARD_NAME, MEDAL_VALUE)
values ('Base', '3');
insert into BASE_CARDS (CARD_NAME, MEDAL_VALUE)
values ('Base', '3');
insert into BASE_CARDS (CARD_NAME, MEDAL_VALUE)
values ('Base', '3');


-- Barracks
insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1_VALUE)
values ('Engineer', '1', '0');
insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1_VALUE)
values ('Engineer', '1', '0');
insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1_VALUE)
values ('Engineer', '1', '0');
insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1_VALUE)
values ('Engineer', '1', '0');
insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1_VALUE)
values ('Engineer', '1', '0');
insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1_VALUE)
values ('Engineer', '1', '0');
insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1_VALUE)
values ('Engineer', '1', '0');
insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1_VALUE)
values ('Engineer', '1', '0');
insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1_VALUE)
values ('Engineer', '1', '0');
insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1_VALUE)
values ('Engineer', '1', '0');
insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1_VALUE)
values ('Engineer', '1', '0');
insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1_VALUE)
values ('Engineer', '1', '0');
insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1_VALUE)
values ('Engineer', '1', '0');
insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1_VALUE)
values ('Engineer', '1', '0');
insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1_VALUE)
values ('Engineer', '1', '0');
insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1_VALUE)
values ('Engineer', '1', '0');
insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1_VALUE)
values ('Engineer', '1', '0');
insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1_VALUE)
values ('Engineer', '1', '0');
insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1_VALUE)
values ('Engineer', '1', '0');
insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1_VALUE)
values ('Engineer', '1', '0');
insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1, SKILL1_VALUE)
values ('Technician', '0', 'RESEARCH', '1');
insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1, SKILL1_VALUE)
values ('Technician', '0', 'RESEARCH', '1');
insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1, SKILL1_VALUE)
values ('Technician', '0', 'RESEARCH', '1');
insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1, SKILL1_VALUE)
values ('Technician', '0', 'RESEARCH', '1');
insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1, SKILL1_VALUE)
values ('Technician', '0', 'RESEARCH', '1');
insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1, SKILL1_VALUE)
values ('Volunteer', '0', 'RECRUITMENT', '0');
insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1, SKILL1_VALUE)
values ('Volunteer', '0', 'RECRUITMENT', '0');
insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1, SKILL1_VALUE)
values ('Volunteer', '0', 'RECRUITMENT', '0');
insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1, SKILL1_VALUE)
values ('Volunteer', '0','RECRUITMENT', '0');
insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1, SKILL1_VALUE)
values ('Volunteer', '0','RECRUITMENT', '0');


--Achievements
insert into ACHIEVEMENT_CARDS (CARD_NAME, MEDAL_VALUE)
values ('Destroyed bases', '5');
insert into ACHIEVEMENT_CARDS (CARD_NAME, MEDAL_VALUE)
values ('Light tanks', '5');
insert into ACHIEVEMENT_CARDS (CARD_NAME, MEDAL_VALUE)
values ('Medium tanks', '5');
insert into ACHIEVEMENT_CARDS (CARD_NAME, MEDAL_VALUE)
values ('Heavy tanks', '5');
insert into ACHIEVEMENT_CARDS (CARD_NAME, MEDAL_VALUE)
values ('Artillery', '5');
insert into ACHIEVEMENT_CARDS (CARD_NAME, MEDAL_VALUE)
values ('Special units', '5');
insert into ACHIEVEMENT_CARDS (CARD_NAME, MEDAL_VALUE)
values ('French medals', '5');
insert into ACHIEVEMENT_CARDS (CARD_NAME, MEDAL_VALUE)
values ('Russian medals', '5');
insert into ACHIEVEMENT_CARDS (CARD_NAME, MEDAL_VALUE)
values ('German medals', '5');
insert into ACHIEVEMENT_CARDS (CARD_NAME, MEDAL_VALUE)
values ('USA medals', '5');
insert into ACHIEVEMENT_CARDS (CARD_NAME, MEDAL_VALUE)
values ('Concentrated attack', '5');
insert into ACHIEVEMENT_CARDS (CARD_NAME, MEDAL_VALUE)
values ('Largest unit', '5');