-- insert into CARDS (CARD_NAME, TYPE, MEDAL_VALUE, CARD_VALUE,SKILL1, SKILL1_VALUE, NATIONALITY, ATTACK,CARD_COST,DEFENCE, DEFENDING_CARD_ID,
--                    HEALTH_POINTS, IF_DEFENSIVE, IF_NATIONAL , SKILL2, SKILL2_VALUE, VEHICLE_TYPE)
-- values ('AMX 12t','Achievement', '1', '0', '1', '1', 'Russia', '1', '5', '2', '0', '3', '0', TRUE, 'strzał z laczka','1','Light');
--

insert into CARDS (CARD_TYPE ,CARD_NAME, TYPE, MEDAL_VALUE)
values ('BaseCard','ZADUPIE BUNKIER','Base', '1');

-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
-- values ('AMX 12t', '1', '0', '1', 'FRENCH', '1', '1', '100', 'LIGHT', '0', '0', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
-- values ('AMX 40', '0', '0', '1', 'FRENCH', '1', '1', '100', 'LIGHT', 'RESEARCH', '2', '0', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
-- values ('D1', '0', '0', '1', 'FRENCH', '1', '1', '100', 'LIGHT', '0', '0', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
-- values ('Hotchkiss H38', '0', '0', '1', 'FRENCH', '1', '1', '100', 'LIGHT', 'REINFORCEMENTS', '1', '0', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
-- values ('AMX 13-90', '1', '0', '1', 'FRENCH', '1', '1', '100', 'LIGHT', 'RECRUITMENT', '0', '0', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
-- values ('AMX 13-75', '1', '0', '1', 'FRENCH', '1', '1', '100', 'LIGHT', 'REINFORCEMENTS', '1', '0', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
-- values ('Hotchkiss H39', '0', '0', '1', 'FRENCH', '1', '1', '100', 'LIGHT', 'DISASSEMBLY', '0', '0', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
-- values ('AMX 38', '0', '0', '1', 'FRENCH', '1', '1', '100', 'LIGHT', 'SCOUT', '0', '0', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
-- values ('Hotchkiss H35', '0', '0', '1', 'FRENCH', '1', '1', '100', 'LIGHT', 'RECRUITMENT', '0', '0', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
-- values ('Bat Chatillon 25t', '2', '0', '3', 'FRENCH', '1', '2', '100', 'MEDIUM', 'DISASSEMBLY', '0', '0', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
-- values ('Renault G1R', '2', '0', '3', 'FRENCH', '1', '2', '100', 'MEDIUM', 'REINFORCEMENTS', '3', '0', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
-- values ('Lorraine 40t', '2', '0', '3', 'FRENCH', '1', '2', '100', 'MEDIUM', 'SIEGE', '0', '0', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
-- values ('D2', '2', '0', '3', 'FRENCH', '1', '2', '100', 'MEDIUM', '0','0', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
-- values ('AMX M4', '5', '0', '6', 'FRENCH', '2', '2', '100', 'HEAVY', 'INDESTRUCTIBILITY', '0', '0', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
-- values ('B1', '3', '0', '4', 'FRENCH', '2', '2', '100', 'HEAVY', '0', '0', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
-- values ('ARL 44', '4', '0', '5', 'FRENCH', '2', '2', '100', 'HEAVY', 'REINFORCEMENTS', '3', '0', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
-- values ('Panzejäger 35R', '1', '0', '2', 'FRENCH', '2', '1', '100', 'TANK_DESTROYER', 'REINFORCEMENTS', '2', '0', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
-- values ('AMX 13 FL 11', '1', '0', '2', 'FRENCH', '2', '1', '100', 'TANK_DESTROYER', 'RESEARCH', '3', '0', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
-- values ('Lorraine 37 LAC', '1', '0', '2', 'FRENCH', '2', '1', '100', 'TANK_DESTROYER', 'SABOTAGE', '0', '0', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
-- values ('Lorraine 39 LAM', '1', '0', '2', 'FRENCH', '2', '1', '100', 'ARTILLERY', 'DISASSEMBLY', '0', '0', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
-- values ('Renault BS', '1', '0', '2', 'FRENCH', '2', '1', '100', 'ARTILLERY', '0', '0', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
-- values ('Lorraine 155', '2', '0', '3', 'FRENCH', '2', '1', '100', 'ARTILLERY', 'DISASSEMBLY', '0', '0', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
-- values ('AMX 105', '2', '0', '3', 'FRENCH', '2', '1', '100', 'ARTILLERY', '0', '0', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
-- values ('Canon de 155 mm', '0', '0', '0', 'FRENCH', '1', '0', '100', 'SPECIAL', 'RECRUITMENT', '0', '0', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1_VALUE, SKILL2_VALUE, DEFENDING_CARD_ID)
-- values ('CT Classe Jaguar', '5', '1', '1', 'FRENCH', '1', '0', '100', 'SPECIAL', '0', '0', '0');
-- insert into VEHICLE_CARDS (CARD_NAME, CARD_VALUE, IF_NATIONAL, CARD_COST, NATIONALITY, ATTACK, DEFENCE, HEALTH_POINTS, VEHICLE_TYPE, SKILL1, SKILL1_VALUE, SKILL2, SKILL2_VALUE, DEFENDING_CARD_ID)
-- values ('Troupes de marine', '1', '0', '0', 'FRENCH', '0', '0', '100', 'SPECIAL', 'SCOUT', '0', 'RECRUITMENT', '0', '0');
--
-- -- Medals
-- -- French
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('French Medal', '1', '1', 'FRENCH');
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('French Medal', '1', '1', 'FRENCH');
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('French Medal', '1', '1', 'FRENCH');
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('French Medal', '1', '1', 'FRENCH');
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('French Medal', '1', '1', 'FRENCH');
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('French Medal', '1', '1', 'FRENCH');
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('French Medal', '1', '1', 'FRENCH');
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('French Medal', '1', '1', 'FRENCH');
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('French Medal', '1', '1', 'FRENCH');
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('French Medal', '1', '2', 'FRENCH');
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('French Medal', '1', '2', 'FRENCH');
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('French Medal', '1', '2', 'FRENCH');
--
-- -- Russian
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('Russian Medal', '1', '1', 'RUSSIAN');
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('Russian Medal', '1', '1', 'RUSSIAN');
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('Russian Medal', '1', '1', 'RUSSIAN');
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('Russian Medal', '1', '1', 'RUSSIAN');
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('Russian Medal', '1', '1', 'RUSSIAN');
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('Russian Medal', '1', '1', 'RUSSIAN');
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('Russian Medal', '1', '1', 'RUSSIAN');
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('Russian Medal', '1', '1', 'RUSSIAN');
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('Russian Medal', '1', '1', 'RUSSIAN');
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('Russian Medal', '1', '2', 'RUSSIAN');
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('Russian Medal', '1', '2', 'RUSSIAN');
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('Russian Medal', '1', '2', 'RUSSIAN');
--
-- -- German
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('German Medal', '1', '1', 'GERMAN');
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('German Medal', '1', '1', 'GERMAN');
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('German Medal', '1', '1', 'GERMAN');
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('German Medal', '1', '1', 'GERMAN');
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('German Medal', '1', '1', 'GERMAN');
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('German Medal', '1', '1', 'GERMAN');
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('German Medal', '1', '1', 'GERMAN');
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('German Medal', '1', '1', 'GERMAN');
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('German Medal', '1', '1', 'GERMAN');
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('German Medal', '1', '2', 'GERMAN');
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('German Medal', '1', '2', 'GERMAN');
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('German Medal', '1', '2', 'GERMAN');
--
-- -- USA
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('USA Medal', '1', '1', 'USA');
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('USA Medal', '1', '1', 'USA');
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('USA Medal', '1', '1', 'USA');
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('USA Medal', '1', '1', 'USA');
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('USA Medal', '1', '1', 'USA');
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('USA Medal', '1', '1', 'USA');
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('USA Medal', '1', '1', 'USA');
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('USA Medal', '1', '1', 'USA');
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('USA Medal', '1', '1', 'USA');
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('USA Medal', '1', '2', 'USA');
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('USA Medal', '1', '2', 'USA');
-- insert into MEDAL_CARDS (CARD_NAME, CARD_VALUE, MEDAL_VALUE, NATIONALITY)
-- values ('USA Medal', '1', '2', 'USA');
--
--
-- -- Bases
-- insert into BASE_CARDS (CARD_NAME, MEDAL_VALUE)
-- values ('Base', '3');
-- insert into BASE_CARDS (CARD_NAME, MEDAL_VALUE)
-- values ('Base', '3');
-- insert into BASE_CARDS (CARD_NAME, MEDAL_VALUE)
-- values ('Base', '3');
-- insert into BASE_CARDS (CARD_NAME, MEDAL_VALUE)
-- values ('Base', '3');
-- insert into BASE_CARDS (CARD_NAME, MEDAL_VALUE)
-- values ('Base', '3');
-- insert into BASE_CARDS (CARD_NAME, MEDAL_VALUE)
-- values ('Base', '3');
-- insert into BASE_CARDS (CARD_NAME, MEDAL_VALUE)
-- values ('Base', '3');
-- insert into BASE_CARDS (CARD_NAME, MEDAL_VALUE)
-- values ('Base', '3');
-- insert into BASE_CARDS (CARD_NAME, MEDAL_VALUE)
-- values ('Base', '3');
-- insert into BASE_CARDS (CARD_NAME, MEDAL_VALUE)
-- values ('Base', '3');
-- insert into BASE_CARDS (CARD_NAME, MEDAL_VALUE)
-- values ('Base', '3');
-- insert into BASE_CARDS (CARD_NAME, MEDAL_VALUE)
-- values ('Base', '3');
-- insert into BASE_CARDS (CARD_NAME, MEDAL_VALUE)
-- values ('Base', '3');
-- insert into BASE_CARDS (CARD_NAME, MEDAL_VALUE)
-- values ('Base', '3');
-- insert into BASE_CARDS (CARD_NAME, MEDAL_VALUE)
-- values ('Base', '3');
--
--
-- -- Barracks
-- insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1_VALUE)
-- values ('Engineer', '1', '0');
-- insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1_VALUE)
-- values ('Engineer', '1', '0');
-- insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1_VALUE)
-- values ('Engineer', '1', '0');
-- insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1_VALUE)
-- values ('Engineer', '1', '0');
-- insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1_VALUE)
-- values ('Engineer', '1', '0');
-- insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1_VALUE)
-- values ('Engineer', '1', '0');
-- insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1_VALUE)
-- values ('Engineer', '1', '0');
-- insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1_VALUE)
-- values ('Engineer', '1', '0');
-- insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1_VALUE)
-- values ('Engineer', '1', '0');
-- insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1_VALUE)
-- values ('Engineer', '1', '0');
-- insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1_VALUE)
-- values ('Engineer', '1', '0');
-- insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1_VALUE)
-- values ('Engineer', '1', '0');
-- insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1_VALUE)
-- values ('Engineer', '1', '0');
-- insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1_VALUE)
-- values ('Engineer', '1', '0');
-- insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1_VALUE)
-- values ('Engineer', '1', '0');
-- insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1_VALUE)
-- values ('Engineer', '1', '0');
-- insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1_VALUE)
-- values ('Engineer', '1', '0');
-- insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1_VALUE)
-- values ('Engineer', '1', '0');
-- insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1_VALUE)
-- values ('Engineer', '1', '0');
-- insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1_VALUE)
-- values ('Engineer', '1', '0');
-- insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1, SKILL1_VALUE)
-- values ('Technician', '0', 'RESEARCH', '1');
-- insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1, SKILL1_VALUE)
-- values ('Technician', '0', 'RESEARCH', '1');
-- insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1, SKILL1_VALUE)
-- values ('Technician', '0', 'RESEARCH', '1');
-- insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1, SKILL1_VALUE)
-- values ('Technician', '0', 'RESEARCH', '1');
-- insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1, SKILL1_VALUE)
-- values ('Technician', '0', 'RESEARCH', '1');
-- insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1, SKILL1_VALUE)
-- values ('Volunteer', '0', 'RECRUITMENT', '0');
-- insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1, SKILL1_VALUE)
-- values ('Volunteer', '0', 'RECRUITMENT', '0');
-- insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1, SKILL1_VALUE)
-- values ('Volunteer', '0', 'RECRUITMENT', '0');
-- insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1, SKILL1_VALUE)
-- values ('Volunteer', '0','RECRUITMENT', '0');
-- insert into BARRACKS_CARDS (CARD_NAME, CARD_VALUE, SKILL1, SKILL1_VALUE)
-- values ('Volunteer', '0','RECRUITMENT', '0');
--
--
-- --Achievements
-- insert into ACHIEVEMENT_CARDS (CARD_NAME, MEDAL_VALUE)
-- values ('Destroyed bases', '5');
-- insert into ACHIEVEMENT_CARDS (CARD_NAME, MEDAL_VALUE)
-- values ('Light tanks', '5');
-- insert into ACHIEVEMENT_CARDS (CARD_NAME, MEDAL_VALUE)
-- values ('Medium tanks', '5');
-- insert into ACHIEVEMENT_CARDS (CARD_NAME, MEDAL_VALUE)
-- values ('Heavy tanks', '5');
-- insert into ACHIEVEMENT_CARDS (CARD_NAME, MEDAL_VALUE)
-- values ('Artillery', '5');
-- insert into ACHIEVEMENT_CARDS (CARD_NAME, MEDAL_VALUE)
-- values ('Special units', '5');
-- insert into ACHIEVEMENT_CARDS (CARD_NAME, MEDAL_VALUE)
-- values ('French medals', '5');
-- insert into ACHIEVEMENT_CARDS (CARD_NAME, MEDAL_VALUE)
-- values ('Russian medals', '5');
-- insert into ACHIEVEMENT_CARDS (CARD_NAME, MEDAL_VALUE)
-- values ('German medals', '5');
-- insert into ACHIEVEMENT_CARDS (CARD_NAME, MEDAL_VALUE)
-- values ('USA medals', '5');
-- insert into ACHIEVEMENT_CARDS (CARD_NAME, MEDAL_VALUE)
-- values ('Concentrated attack', '5');
-- insert into ACHIEVEMENT_CARDS (CARD_NAME, MEDAL_VALUE)
-- values ('Largest unit', '5');